### PR TITLE
Update code for biopython 1.83 compatibility

### PR DESCRIPTION
**Pull request by MatBarba**
The `strand` information is now solely found in the `SeqFeature.location` attribute

This should be the only thing that blocks the upgrade from 1.81 to 1.83

### CODE REVIEW

**Comment by MatBarba** [comment]
On hold, mypy complains about how we get `sub_features()`

**Review by vsitnik — APPROVED** [review]
Thank you!

**Review by JAlvarezJarreta — COMMENTED** [review]
The only bit remaining is `"SeqFeature" has no attribute "sub_features"  [attr-defined]`, almost there!

**Comment by MatBarba** [comment]
This branch is quite old and has a lot of conflicts, we might want to restart from the current main instead

**Comment by MatBarba** [comment]
Closed in favor of https://github.com/Ensembl/ensembl-genomio/pull/391, more up to date and more complete

**Pull request closed without merging**
