### PR TITLE
Add Python build and publication to PyPI pipeline

### PR DESCRIPTION
**Pull request by JAlvarezJarreta**
The current approach follows a documentation generation only when a release happens, avoiding updates in the documentation of functionality not yet released in PyPI (thus why the previous mkdocs pipeline has been removed).

### CODE REVIEW

**Review by ens-LCampbell — APPROVED** [review]
Yeah looks fine to me

**Comment by MatBarba** [comment]
Can you give more details on what this PR does? Is it adding building and publishing to pypi automatically? When is this process run?

**Comment by JAlvarezJarreta** [comment]
@MatBarba sure! So this PR updates some bits of the documentation (adding code of conduct page), and add a new GitHub Actions pipeline to generate the documentation and publishing the library to PyPI when a new release is published in GitHub. As part of the changes, the current documentation pipeline is dropped since it makes more sense to update the GitHub pages when a release is done, to avoid adding features to the documentation not yet released.

**Review by MatBarba — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
