### PR TITLE
Updates to check_json_schmea NXF module & python

### PR DESCRIPTION
**Pull request by ens-LCampbell**

### CODE REVIEW

**Review by MatBarba — APPROVED** [review]
Looks good to me

**Comment by ens-LCampbell** [comment]
Would you mind to merge @MatBarba thanks

**Review by MatBarba — CHANGES_REQUESTED** [review]
Pytest is failing, I guess because of the function name change

**Comment by ens-LCampbell** [comment]
thanks for updates to pytests @MatBarba I had just started to look into pytest for schema validator.

**Pull request merged**
