### PR TITLE
Restructure the tree folder of the repository

### PR DESCRIPTION
**Pull request by JAlvarezJarreta**
This does not include the work under the python section, since this would require too many code updates (not worth it since we are migrating the codebase at this very moment anyway). This is how the tree folder looks like now (with empty file examples for the `pipelines` folder):
```
ensembl-genomio
├── config
│   └── external_db_map
│       ├── default.txt
│       └── minimal.txt
├── data
│   └── test
│       ├── exon_cds_duplicated_ids_test.gff3
│       ├── gene_cds_test.gff3
│       ├── pre_mirna_test.gff3
│       └── sub_rule_test.gff3
├── docs
├── LICENSE
├── NOTICE
├── pipelines
│   └── nextflow
│       ├── conf
│       │   └── base.config
│       ├── modules
│       │   └── process_fasta.nf
│       ├── subworkflows
│       │   └── genome_validation.nf
│       └── workflows
│           ├── genome_loader
│           │   ├── genome_loader.nf
│           │   └── nextflow.config
│           └── nexflow.config
├── pyproject.toml
├── README.md
├── schemas
│   ├── functional_annotation_schema.json
│   ├── genome_schema.json
│   ├── manifest_schema.json
│   ├── README.md
│   ├── seq_attrib_schema.json
│   └── seq_region_schema.json
├── scripts
├── setup.py
└── src
    ├── containers
    ├── perl
    └── python
```
_Note:_ I have hidden the content of those folders left unchanged.

The changes proposed here are not meant to be final, but taken as a first point of discussion. Feel free to give as many comments/feedback as needed, so all the items can be discussed during our next software development meeting.

### CODE REVIEW

**Comment by MatBarba** [comment]
I'm wondering what will be the best way to merge our current changes if we merge this first?
I assume we'd want to mimick the structure first before making a PR?

**Comment by vsitnik** [comment]
not sure, that schemas are data

**Comment by MatBarba** [comment]
I would suggest adding a level under "pipelines" with a folder explicitely named "nextflow" (similar to src -> perl, python)

**Comment by MatBarba** [comment]
> not sure, that schemas are data

metadata then?

**Comment by vsitnik** [comment]
and metacode :)

**Review by vsitnik — APPROVED** [review]
ok. cool

**Review by ens-LCampbell — COMMENTED** [review]
Are we happy with the set up of lib | src regards importing PERL modules ? If so Im happy to approve

**Review by MatBarba — APPROVED** [review]
Tested with prepare_pipeline, which among other things uses the schemas and external data

**Comment by JAlvarezJarreta** [comment]
> Tested with prepare_pipeline, which among other things uses the schemas and external data

Thank you for the test!

**Review by Dishalodha — APPROVED** [review]
I like this structure, I am happy it :)

**Pull request merged**
